/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 D:\Portfolio\Portfolio\public\Models\background.gltf
Author: McWinterL (https://sketchfab.com/winterlea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scifi-platform-stage-scene-baked-64adb59a716d43e5a8705ff6fe86c0ce
Title: scifi platform stage scene baked
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Background(props) {
  const { nodes, materials } = useGLTF('/Models/background.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Black_Ground_Black_0.geometry} material={materials.Black} position={[-226.26, 508.73, 304]} />
        <mesh geometry={nodes['Black_Wall_Black-Wall_0'].geometry} material={materials['Black-Wall']} position={[-226.26, 508.73, 304]} />
        <mesh geometry={nodes['Black_LightUpper_Black-Upper_0'].geometry} material={materials['Black-Upper']} position={[-226.26, 508.73, 304]} />
        <mesh geometry={nodes.Emissive_Cyan__0.geometry} material={materials.Emissive_Cyan__0} position={[-113.13, 107.46, 152]} />
        <mesh geometry={nodes['Emissive_Red_Emissive-Red_0'].geometry} material={materials['Emissive-Red']} position={[4.63, 438.37, 304]} />
        <mesh geometry={nodes['Light_Upper_Light-Upper_0'].geometry} material={materials['Light-Upper']} position={[-461.79, 451.18, 32.13]} />
        <mesh geometry={nodes['3_Wall_Hori_1__0'].geometry} material={materials.Emissive_Cyan__0} position={[0, 474.31, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/background.gltf')
