/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 D:\Portfolio\Portfolio\public\Models\carved2.glb
Author: Virtual Museums of Małopolska (https://sketchfab.com/WirtualneMuzeaMalopolski)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/carved-lacquer-box-341500e6ceec44f4aea3db16c4fe000b
Title: Carved lacquer box
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/carved2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.15, 0.16]} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['15570_1069_V_Pudelko_06_FIN_Material_u1_v1']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['15570_1069_V_Pudelko_06_FIN_Material_u1_v1']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['15570_1069_V_Pudelko_06_FIN_Material_u1_v1']} />
      </group>
    </group>
  )
}

useGLTF.preload('/carved2.glb')
