/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 D:\Portfolio\Portfolio\public\Models\3Bt--Dinosaur.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { MaterialLoader } from 'three'
export function Dino({props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Models/3Bt--Dinosaur.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="mesh">
          <skinnedMesh name="Trex_15k_Eyes_Geo" geometry={nodes.Trex_15k_Eyes_Geo.geometry} material={materials.eyes_Mat} skeleton={nodes.Trex_15k_Eyes_Geo.skeleton} position={[0, 1.41, 0.08]} />
          <skinnedMesh name="Trex_15k_Body_Geo" geometry={nodes.Trex_15k_Body_Geo.geometry} material={materials.body_Mat}  skeleton={nodes.Trex_15k_Body_Geo.skeleton}   />
        </group>
        <primitive object={nodes.root} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/3Bt--Dinosaur.glb')
